"""Pure helpers for Jira attachment fetch (no HTTP)."""

from __future__ import annotations

import html
import re

__version__ = "1.1.0"

ISSUE_FIELDS = (
    "summary,description,attachment,status,issuetype,priority,assignee,reporter,"
    "created,updated,labels,components,resolution"
)


def html_rendered_to_plain(html_blob: str) -> str:
    """Coarse strip of Jira renderedBody HTML to readable plain text."""
    if not html_blob or not str(html_blob).strip():
        return ""
    text = str(html_blob)
    text = re.sub(r"(?i)<br\s*/?>", "\n", text)
    text = re.sub(r"(?i)</(p|div|h[1-6])>", "\n", text)
    text = re.sub(r"(?i)<(p|div)[^>]*>", "", text)
    text = re.sub(r"<[^>]+>", " ", text)
    text = html.unescape(text)
    text = re.sub(r"[ \t\r\f\v]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return "\n".join(line.rstrip() for line in text.splitlines()).strip()


def build_comments_digest(issue_key: str, comments_payload: dict) -> str:
    lines: list[str] = [
        f"# {issue_key} — Jira 评论摘要 (comments_digest.txt)",
        f"# Generated by fetch_jira_attachments.py v{__version__}",
        "",
    ]
    for comment in comments_payload.get("comments") or []:
        comment_id = comment.get("id", "")
        created = comment.get("created", "")
        author = (comment.get("author") or {}).get("displayName", "")
        body_html = comment.get("renderedBody")
        if body_html is None or body_html == "":
            plain = "[无 renderedBody；见 comments.json 的 body/ADF]"
        else:
            plain = html_rendered_to_plain(str(body_html))
        if not (plain and plain.strip()):
            plain = "[无文本可抽取（常为纯图/媒体）；见 Jira 或 comments.json]"
        lines.append(f"--- id={comment_id}  {created}  {author} ---")
        lines.append(plain)
        lines.append("")
    if len(comments_payload.get("comments") or []) == 0:
        lines.append("(无评论)")
    return "\n".join(lines).rstrip() + "\n"


def issue_brief_for_manifest(issue: dict) -> dict:
    fields = issue.get("fields") or {}
    status = fields.get("status")
    status_name = (status or {}).get("name") if isinstance(status, dict) else None
    issue_type = fields.get("issuetype")
    issue_type_name = (issue_type or {}).get("name") if isinstance(issue_type, dict) else None
    assignee = fields.get("assignee")
    assignee_name = (
        (assignee or {}).get("displayName") if isinstance(assignee, dict) else None
    )
    priority = fields.get("priority")
    priority_name = None
    if isinstance(priority, dict):
        priority_name = priority.get("name") or priority.get("displayName")
    elif priority is not None:
        priority_name = str(priority)
    return {
        "summary": fields.get("summary"),
        "status": status_name,
        "issueType": issue_type_name,
        "assignee": assignee_name,
        "updated": fields.get("updated"),
        "priority": priority_name,
    }
